name: Compile And Release

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository...
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Download AndroidModLoader`s mod template...
      uses: wei/wget@v1
      with:
        args: -O ./AML_src.zip https://github.com/RusJJ/AndroidModLoader/archive/refs/heads/main.zip

    - name: Install AndroidModLoader`s mod template...
      run: |
        unzip ./AML_src.zip
        mv ./AndroidModLoader-main/mod ./mod

    - name: Install Android NDK (r25c)...
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r25c
        local-cache: true

    - name: Build the code...
      run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk NDK_DEBUG=0 -j12

    - name: Upload the mod!
      uses: actions/upload-artifact@v3
      with:
        name: crashInfo.zip
        path: ./libs

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.run_number }}
          release_name: Release_CrashInfo ${{ github.run_number }}


    - name: check dir
      run: |
        ls -a
        tree ./
        
    - name: Upload Release Asset (test)
      id: upload-release-asset 
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
